CREATE TABLE Categories (
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,

    Name NVARCHAR(250) NOT NULL,
    Description NVARCHAR(1000) NULL,
    
    ParentCategoryID UNIQUEIDENTIFIER NULL,

    IsActive BIT DEFAULT 1,

    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME NULL,
    IsDeleted BIT DEFAULT 0,
    DeletedAt DATETIME NULL
);